TARGET		= picodon
OBJS_TARGET	= picodon.o config.o messages.o

CFLAGS = -g
# optimization
#CFLAGS+= -O2
# Use $XDG_CONFIG_HOME or ~/.config dir to save config files
CFLAGS+= -DSUPPORT_XDG_BASE_DIR

LIBS = -lcurl -lpthread -lm

include Makefile.in
